' Gambas module file

Public YuzuInstallFolder As String
Public RyujinxInstallFolder As String
Public AlwaysUseCloudFlare As Short
Public CloudFlareReverseProxyUrl As String
Public DownloadSource As String
Public AliyundriveDomain As String
Public AutoCheckForUpdate As Short

Public TempBrowse As String


Public Function OpenFileChooseDialog() As String
    TempBrowse = ""
    frmFileChooser.show
    Do While TempBrowse = ""
        Wait 0.01
    Loop
    If TempBrowse = "Cancel" Then 
        Return ""
    Else
        Return TempBrowse
    Endif
End

Public Sub WriteConfig()  
    Settings.Write(YuzuInstallFolder, ["Folder/YuzuInstallFolder"])
    Settings.Write(RyujinxInstallFolder, ["Folder/RyujinxInstallFolder"])
    Settings.Write(AlwaysUseCloudFlare, ["Network/AlwaysUseCloudFlare"])
    Settings.Write(DownloadSource, ["Network/DownloadSource"])
    Settings.Write(AutoCheckForUpdate, ["Tool/AutoCheckForUpdate"])
End
